### PR TITLE
Multistage build and standardize build id

### PR DESCRIPTION
**Pull request by carkod**
## Done

Implemented multistage build to reduce docker image sizes using reference from ubuntu.com

## QA

- Changes should not affect site
- Check image size: `docker build --tag myimage && docker images` check myimage size
- Revision ID is correctly added in the headers: `docker build --tag myimage --build-arg BUILD_ID=myfakeid .`
- `docker run -ti -p 8111:80 myimage`
- `curl -I http://localhost:8111` to see if headers display "myfakeid"

## Issue / Card

- Multistage builds issue (WUB Fix #2142)
- Standardize build-ids (WUB Fix #2096)

### CODE REVIEW

**Comment by jpmartinspt** [comment]
@carkod I'm not sure if @nottrobin told you otherwise, but I think we are missing the build-js and build-css steps on the multi stage build. We seem to be doing it in the ubuntu.com build and if i recall correctly we want to add it to other projects too.

**Comment by carkod** [comment]
@jpmartinspt yeah, I am actually improving it right now

**Comment by carkod** [comment]
## Done

Added additional missing builds

## QA

- Changes should not affect site
- Check image size: `docker build --tag myimage && docker images` check myimage size
- Revision ID is correctly added in the headers: `docker build --tag myimage --build-arg BUILD_ID=myfakeid .`
- `docker run -ti -p 8111:80 myimage`
- `curl -I http://localhost:8111` to see if headers display "myfakeid"

## Issue / Card

- Multistage builds issue (WUB Fix #2142)
- Standardize build-ids (WUB Fix #2096)

**Comment by jpmartinspt** [comment]
Can we please remove the JS dependencies updates from this PR(remove yarn.lock changes)?

**Comment by carkod** [comment]
> Can we please remove the JS dependencies updates from this PR(remove yarn.lock changes)?

What is the default action? Do we usually commit the `yarn.lock` or not?

**Comment by jpmartinspt** [comment]
We commit it, but I don't think we should be updating dependencies on this PR.

**Comment by carkod** [comment]
- Closing this one, as it is using a master branch.
- Opening a new one with a feature branch

**Pull request closed without merging**
