### PR TITLE
Copy update - charmed-osm.com

### PR DESCRIPTION
**Pull request by bethcollins92**
## Done

- Copy changes on - charmed-osm.com
- Add blog widget to home page

## QA

- Check out this feature branch
- Run the site using the command `./run`
- View the site locally in your web browser at: http://0.0.0.0:8042/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check page against [copy doc](https://docs.google.com/document/d/1mKfttykmrc4ub_LkqdRGIE_x9WgR1NGr7ulxrLvIZXk/edit?ts=60224421#heading=h.mbee56yofefb)

## Issue / Card

Fixes [#9224](https://github.com/canonical-web-and-design/ubuntu.com/issues/9224)

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by SirSamTumless** [comment]
I can't see the blog widget?

**Comment by SirSamTumless** [comment]
Sorry to be that guy, but the link shows the icon to open in a new tab but it doesn't; 
Screenshot 2021-02-23 at 10 19 20

**Comment by bethcollins92** [comment]
> Sorry to be that guy, but the link shows the icon to open in a new tab but it doesn't;
> Screenshot 2021-02-23 at 10 19 20

I think this icon means the link takes you to a page that is external to the site you're currently on not necessarily a new tab, unless I'm mistaken @pmahnke ?

**Comment by pmahnke** [comment]
@bethcollins92 is correct @SirSamTumless, that is the external page icon, we don't have a new tab icon

**Comment by SirSamTumless** [comment]
I'll shut ;D

**Review by SirSamTumless — APPROVED** [review]

**Review by SirSamTumless — APPROVED** [review]

**Pull request merged**
